#!/usr/bin/env bash
set -euo pipefail

# Convenience wrapper that drives run-simpa-pruning.sh with mainnet-like defaults.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export SIMPA_DB_DIR="${SIMPA_DB_DIR:-${ROOT_DIR}/pruning-optimisation/baseline/experiments/simpa-db-mainnetish}"
export SIMPA_BPS="${SIMPA_BPS:-10}"
export SIMPA_MINERS="${SIMPA_MINERS:-4}"
export SIMPA_TPB="${SIMPA_TPB:-1400}"
export SIMPA_LONG_PAYLOAD="${SIMPA_LONG_PAYLOAD:-1}"
export SIMPA_RETENTION_DAYS="${SIMPA_RETENTION_DAYS:-0.5}"
export SIMPA_TARGET_BLOCKS="${SIMPA_TARGET_BLOCKS:-120000}"
export SIMPA_DELAY="${SIMPA_DELAY:-0.5}"
export SIMPA_ROCKSDB_STATS="${SIMPA_ROCKSDB_STATS:-1}"
export SIMPA_ROCKSDB_STATS_PERIOD_SEC="${SIMPA_ROCKSDB_STATS_PERIOD_SEC:-30}"
export SIMPA_ROCKSDB_PIPELINED="${SIMPA_ROCKSDB_PIPELINED:-0}"
export SIMPA_FORCE_REBUILD="${SIMPA_FORCE_REBUILD:-0}"
export SIMPA_SKIP_ACCEPTANCE_VALIDATION="${SIMPA_SKIP_ACCEPTANCE_VALIDATION:-1}"
export SIMPA_RUN_LABEL="${SIMPA_RUN_LABEL:-}"

echo ">> Simpa mainnet-ish run"
echo "   SIMPA_DB_DIR=${SIMPA_DB_DIR}"
echo "   SIMPA_BPS=${SIMPA_BPS}, SIMPA_MINERS=${SIMPA_MINERS}, SIMPA_TPB=${SIMPA_TPB}, SIMPA_RETENTION_DAYS=${SIMPA_RETENTION_DAYS}"
echo "   SIMPA_TARGET_BLOCKS=${SIMPA_TARGET_BLOCKS}, SIMPA_LONG_PAYLOAD=${SIMPA_LONG_PAYLOAD}"
echo "   SIMPA_ROCKSDB_STATS=${SIMPA_ROCKSDB_STATS} (period ${SIMPA_ROCKSDB_STATS_PERIOD_SEC}s)"
echo "   SIMPA_ROCKSDB_PIPELINED=${SIMPA_ROCKSDB_PIPELINED}"
echo "   SIMPA_FORCE_REBUILD=${SIMPA_FORCE_REBUILD}"
echo "   SIMPA_SKIP_ACCEPTANCE_VALIDATION=${SIMPA_SKIP_ACCEPTANCE_VALIDATION}"
if [[ -n "${SIMPA_RUN_LABEL}" ]]; then
    echo "   SIMPA_RUN_LABEL=${SIMPA_RUN_LABEL}"
fi
echo "   PRUNE_LOCK_MAX_DURATION_MS=${PRUNE_LOCK_MAX_DURATION_MS:-unset}"
echo "   PRUNE_BATCH_MAX_BLOCKS=${PRUNE_BATCH_MAX_BLOCKS:-unset}"
echo "   PRUNE_BATCH_MAX_BYTES=${PRUNE_BATCH_MAX_BYTES:-unset}"
echo "   PRUNE_BATCH_MAX_OPS=${PRUNE_BATCH_MAX_OPS:-unset}"
echo "   PRUNE_BATCH_MAX_DURATION_MS=${PRUNE_BATCH_MAX_DURATION_MS:-unset}"
echo "   PRUNE_BATCH_BODIES=${PRUNE_BATCH_BODIES:-unset}"

exec "${ROOT_DIR}/pruning-optimisation/run-simpa-pruning.sh" "$@"
